export const API_PRODUCTS_LINK = "https://fakestoreapi.com/products";

export const SEND_PRODUCT_PROPOSAL = "Send product proposal";
export const TOTAL_PRODUCTS = "Total products:";
export const NUMBER_OF_FAVORITES = "Number of favorites:";
export const ADDING_PRODUCT = "Adding product...";
export const ADD_A_PRODUCT = "Add a product";
export const START_TYPING_PRODUCT_DESCRIPTION_HERE_PLACE_HOLDER = "Start typing product description here...";
export const PRICE_PLACE_HOLDER = "Price...";
export const TITLE_PLACE_HOLDER = "Title...";
export const PRODUCT_DETAIL_LABEL = "Product details: *";
export const YOUR_PRODUCT_NEEDS_A_TITLE = "Your product needs a title";
export const YOUR_PRODUCT_NEEDS_SOME_CONTENT = "Your product needs some content";
export const REMOVE_FROM_FAVORITES = "Remove from favorites";
export const ADD_TO_FAVORITES = "Add to favorites";
export const RATING = "Rating:";
export const PRICE = "Price:";
export const DESCRIPTION = "Description:";
export const PRODUCT_TITLE = "Product title: *";
